/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        /* Brand palette mapped to semantic names */
        nada: {
          50: '#faf8fc',
          100: '#f3eef7',
          200: '#e8ddf0',
          300: '#d3a5d4',
          400: '#bb87c7',
          500: '#ab6cbd',
          600: '#a569db',
          700: '#8a4fb0',
          800: '#6e3d8e',
          900: '#542d6b',
        },
        flora: {
          50: '#f8fae8',
          100: '#eef3c8',
          200: '#d6e48e',
          300: '#c6d47d',
          400: '#b9d54b',
          500: '#9ab83d',
          600: '#788150',
          700: '#5e6540',
          800: '#454b30',
          900: '#2c3020',
        },
        blush: {
          50: '#fdf5f9',
          100: '#f8e8f0',
          200: '#f0d1e1',
          300: '#d8b3c9',
          400: '#c98db1',
          500: '#b86e9a',
          600: '#a05580',
          700: '#834568',
          800: '#663550',
          900: '#4a2538',
        },
        sand: {
          50: '#fbfaf3',
          100: '#f5f3e8',
          200: '#eae6d2',
          300: '#d0cfa6',
          400: '#b8b78c',
          500: '#9f9e72',
          600: '#87865c',
          700: '#6d6c49',
          800: '#535237',
          900: '#3a3926',
        },
        /* Semantic aliases using CSS variables */
        astro: {
          50: 'rgb(var(--color-surface) / <alpha-value>)',
          100: 'rgb(var(--color-surface) / <alpha-value>)',
          200: 'rgb(var(--color-border) / <alpha-value>)',
          300: 'rgb(var(--color-muted) / <alpha-value>)',
          400: 'rgb(var(--color-primary) / <alpha-value>)',
          500: 'rgb(var(--color-primary) / <alpha-value>)',
          600: 'rgb(var(--color-button-bg) / <alpha-value>)',
          700: 'rgb(var(--color-button-bg-hover) / <alpha-value>)',
          800: 'rgb(var(--color-foreground) / <alpha-value>)',
          900: 'rgb(var(--color-foreground) / <alpha-value>)',
          950: 'rgb(var(--color-foreground) / <alpha-value>)',
        },
        dark: {
          50: 'rgb(var(--color-background) / <alpha-value>)',
          100: 'rgb(var(--color-surface) / <alpha-value>)',
          200: 'rgb(var(--color-button-bg-hover) / <alpha-value>)',
          300: 'rgb(var(--color-secondary) / <alpha-value>)',
          400: 'rgb(var(--color-secondary) / <alpha-value>)',
          500: 'rgb(var(--color-muted) / <alpha-value>)',
          600: 'rgb(var(--color-border-strong) / <alpha-value>)',
          700: 'rgb(var(--color-border) / <alpha-value>)',
          800: 'rgb(var(--color-surface-strong) / <alpha-value>)',
          900: 'rgb(var(--color-surface) / <alpha-value>)',
          950: 'rgb(var(--color-background) / <alpha-value>)',
        },
        mono: {
          bg: 'rgb(var(--color-background) / <alpha-value>)',
          surface: 'rgb(var(--color-surface) / <alpha-value>)',
          text: 'rgb(var(--color-foreground) / <alpha-value>)',
          secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
          muted: 'rgb(var(--color-muted) / <alpha-value>)',
          border: 'rgb(var(--color-border) / <alpha-value>)',
          button: 'rgb(var(--color-button-bg) / <alpha-value>)',
          buttonText: 'rgb(var(--color-button-text) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Playfair Display"', 'Georgia', 'serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [],
}
